### ISSUE TITLE
 BASELINE As a maintenance administrator, I should be able to login with access to the management program

### ISSUE THREAD

**Issue by rizzi-trevor** [rizzi-trevor/CS1C-2DGraphicsModeler#1]
**Description:**
The program requires an admin login to access admin functionality. The login screen will prompt for a username and a password, and will check for valid input.

**Task:**
- [ ] Text entry for username with label
- [ ] Text entry for password with label
- [ ] Read username
- [ ] Read password
- [ ] [ Login ] button to attempt login
- [ ] [ Clear] button to remove login text
- [ ] Verify login credentials
- [ ] Failed text displays when invalid username or password
- [ ] Upon successful login, display admin window

**Testing:**
- [ ] Attempt with empty username and/or password
- [ ] Attempt with empty incorrect username/password
- [ ] Attempt with a random string to check database works

**Assignee:**
- Trevor

**Priority::**
- 1

**Definition of Done**
Be able to login as an admin using correct username and password, and be redirected to the admin page.

**Story points: 1 BASELINE**
