### ISSUE TITLE
As a maintenance administrator, I should be able to move shapes/text being rendered

### ISSUE THREAD

**Issue by rizzi-trevor** [rizzi-trevor/CS1C-2DGraphicsModeler#10]
**Description:**
After logging in as an administrator, I should be able to move shapes (including text) that are currently being rendered. These changes should be visible in the render area

**Task:**
- [ ] Select any current shape/ text that is being rendered
- [ ] Be able to move that shape in any way while it is being rendered
- [ ] Display the changes in the render area

**Testing:**
- [ ] Attempt with all shapes
- [ ] Ensure the movements pertain with other changes
- [ ] Ensure that changes are displayed in the render area

**Assignee:**
- Trevor

**Priority::**
- 4

**Definition of Done**
Be able to move shapes including text while they are being rendered. The changes should be displayed in the render area.

**Story points: 20**
