### ISSUE TITLE
As a user, I should be able to contact the developers if I have any questions on how to use their software.

### ISSUE THREAD

**Issue by rizzi-trevor** [rizzi-trevor/CS1C-2DGraphicsModeler#2]
**Description:**
Create a way for users to contact the development team.

**Task:**
- [ ] create a contact area in the application
- [ ] Provide an email link that directs the user to the developer's email
- [ ] Team name and logo need to be included in this area

**Testing:**
- [ ] Try to send an email while logged in
- [ ] Send an email as a guest

**Assignee:**
- Conor

**Priority:**
- 10

**Definition of Done:**
A user of the site should be able to easily create an email to contact the developers

**Story points:**
- 5
