### ISSUE TITLE
As a user, I should be able to see a list of all the shapes that I am currently rendering.

### ISSUE THREAD

**Issue by rizzi-trevor** [rizzi-trevor/CS1C-2DGraphicsModeler#3]
**Description:**
All shapes and their properties should be listed in a window.

**Task:**
- [ ] Identify shapes by their type(derived classes from a base shape)
- [ ] Display shape properties: dimensions, pen color, pen width, pen style, pen cap style, pen join style, brush color, brush shape
- [ ] Text properties should also be displayed: shape dimensions, text string, text color, text alignment, text point size, text font family, text font style, text font weight
- [ ] Shapes should be given a unique ID

**Testing:**
- [ ] make sure each type of shape and the properties of the shape are displayed in the window
- [ ] make sure text properties are also displayed
- [ ] test with multiple shapes at once

**Assignee:**
- Connor

**Priority:**
- 4

**Definition of Done:**
All shapes should be displayed in a rendering window, with all their properties listed as well. Text properties should also be listed. Task is complete when all the properties can be accurately displayed and shapes are assigned unique IDs.

**Story points:**
- 15
