### ISSUE TITLE
As a user, I should be able to remove or derender a shape within the editor

### ISSUE THREAD

**Issue by rizzi-trevor** [rizzi-trevor/CS1C-2DGraphicsModeler#4]
**Description:**
The user should be able to remove a render shape or multiple if they decide they
don’t want it to be rendered anymore.

**Task:**
- [ ] Identify if the user wants to remove one or multiple shapes
- [ ] Identify which shape the user wants removed. (By unique ID?)
- [ ] Remove displayed shape and properties: dimensions, pen color,pen width, pen style, pen cap 
       style, pen join style, brush color, brush shape
- [ ] Remove displayed text properties: shape dimensions, text string, text color,
       text alignment, text point size, text font family, text font style, text font weight [ ] [ Login ] 
       button to attempt login

**Testing:**
- [ ] Verify that the correct shape or shapes is identified for removal
- [ ] Verify that the correct shape or shapes is removed
- [ ] Verify that no other shapes are altered or removed other than the ones specified
- [ ] Verify that the removed shapes are no longer rendered

**Assignee:**
- kkwoalak9

**Priority:**
- 2

**Definition of Done:**
User is able to select that they want to remove rendered shapes. Once in the removal
window user is able to see rendered objects and is able to tick which ones they want
for removal. They are then asked to confirm before selected shapes are removed from the
render window.

**Story points:**
- 20
