### ISSUE TITLE
As a user, I should be able to edit and update a rendered shape

### ISSUE THREAD

**Issue by rizzi-trevor** [rizzi-trevor/CS1C-2DGraphicsModeler#5]
**Description:**
The user should be able to edit an existing or rendered shape. Which then would be
Updated with the edited stats and re-rendered.
 
**Task:**
- [ ] Identify if the user wants to edit one or multiple shapes
- [ ] Identify which shape the user wants to edit. (By unique ID?)
- [ ] Update the displayed shape with new edited properties: dimensions, pen color, pen width, pen 
       style, pen cap style, pen join style, brush color, brush shape
- [ ] Update the displayed text properties to match the new edited properties: shape dimensions, 
       text string, text color, text alignment, text point size, text font family, text font style, text font 
       weight
- [ ] Call the remove / de-render function on the edited shapes
- [ ] Re-render the updated shapes with the new properties
 
**Testing:**
- [ ] Verify that the correct shape or shapes is identified for editing
- [ ] Verify that if the user tries to update multiple shapes at the same time, that they are the same 
       shape.
- [ ] Verify that the correct shape or shapes is edited and updated
- [ ] Verify that no other shapes are altered or edited other than the ones specified
- [ ] Verify that the edited shapes are removed / de-rendered
- [ ] Verify that the edited shapes are re-rendered with the updated characteristics
 
**Assignee:**
- kkwoalak9

**Priority:**
- 3
 
**Definition of Done:**
Users are able to select that they want to edit rendered shapes. Once in the edit
window the user is able to see rendered objects and is able to tick which ones they want
To edit. They are then able to update the characteristics of the selected shapes either
One at a time or multiple at a time if they are the same shape. They are then asked to
confirm before selected shapes are updated and re-rendered.
 
**Story points:**
- 25
