### ISSUE TITLE
As a maintenance administrator, I should be able to modify a shape's properties

### ISSUE THREAD

**Issue by rizzi-trevor** [rizzi-trevor/CS1C-2DGraphicsModeler#6]
**Description:**
After an admin has successfully logged into the management program, they should be able to modify the properties of each shape in the drawing tool. They will be greeted with a menu that allows them to select a shape, and then each of the properties of that shape. 

**Task:**
- [ ] List of shapes
- [ ] Ability to select shape
- [ ] Show current shape properties
- [ ] Give ability to change the shape properties
- [ ] Property changes should remain consistent for the program

**Testing:**
- [ ] Verify correct shapes/properties are displayed
- [ ] Verify that changed property retains the changes
- [ ] Attempt to make invalid changes

**Assignee:**
- rizzi-trevor

**Priority::**
- 6

**Definition of Done**
Be able to select any shape in the program, and change its base properties

**Story points: 20**
