### ISSUE TITLE
As a user, I should be able to see a list of the shapes (with all their properties) sorted by their shape ID

### ISSUE THREAD

**Issue by rizzi-trevor** [rizzi-trevor/CS1C-2DGraphicsModeler#7]
**Description:**
User should be able to get a list of all shapes sorted by shape ID in ascending order

**Tasks:**

- [ ] Clear the user's screen
- [ ] Prompt user for a shape ID input
- [ ] Sort through every rendered shape for desired shape ID
- [ ] Clear the screen of any shapes that do not meet this criteria
- [ ] Display the desired shapes' information (type, dimensions, pen color, pen width, pen style, pen cap style, pen join style, brush color, and brush style)

**Testing:**

- [ ] Verify that all shapes in user library are included
- [ ] Verify that the ID's are in the right order
- [ ] Verify that all the shapes' information is displayed and that it is correct
- [ ] Verify that the function works multiple times in a row as well as after other functions
- [ ] Verify that no shapes are removed or altered during the process

**Assignee:**

- hannahjo9

**Priority:**

- 5

**Definition of Done:**
User is able to display a list of shapes with a shape ID of their choice at any time without altering any information to do so.

**Extra Notes:**

- Could add a sorting in descending order option

**Story points:**
- 8
