### ISSUE TITLE
As a user I should be able to produce a list of shapes with a specific area that I can input.

### ISSUE THREAD

**Issue by rizzi-trevor** [rizzi-trevor/CS1C-2DGraphicsModeler#8]
**Description:**
User should be able to easily sort through all rendered shapes for a certain area, that will display those shapes' information.

**Tasks:**

- [ ] Clear the user's screen
- [ ] Prompt user for an area input
- [ ] Sort through every rendered shape with the desired area
- [ ] Display the desired shapes' type, ID, and area. 
- [ ] Display some sort of error message if an unused area or non-numerical character is entered

**Testing:**

- [ ] Check that the area the user enters is the area being used to sort
- [ ] Verify that only the desired shapes are shown
- [ ] Verify that that shape/ those shape's information is displayed
- [ ] Verify that the function works multiple times in a row with complete accuracy
- [ ] Verify that all shapes remain in the user library and that none are removed or added

**Assignee:**

- hannahjo9

**Priority:**

- 7

**Definition of Done:**
User is able to display shapes by an area of their choice at any time without altering any information in doing so.

**Extra notes:**

- Not sure how necessary this would be but we could incorporate code that would search for an area close to the one entered if there were no exact results, provide some options as to what similar areas they could choose
-  We could also include a list of the shapes of the library with their shape type and area displayed

**Story points:**
- 15
